### ISSUE TITLE
Feature: Have all channels log to one log file

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#10]
# Bug

## Expected behavior
Log all channels on a server to a single file

## Actual behavior
Logs all channels to separate files and mircstats gives error about overlapping timestamps when you try to analyze all logs from server.

# Feature
I wish to generate mircstats from the whole server, but all channels are logged to separate .log files, which makes mircstats ignore log files because of overlapping timestamps.

If all channels from the server were logged to one file, this wouldn't be a problem.

**Comment by ikoutone** [comment]
Created a small .bat file to combine all logs, sort by the timestamp and add the channel info at the top, so this feature request isn't so urgent anymore, but would be nice to have still.

**Comment by MJHeijster** [comment]
In mircstats you can do a wildcard for the logs (e.g. C:\bots\statbot\serverid\*.log. It's really easy to implement so I'll do it soon with an option in the xml.

**Comment by MJHeijster** [comment]
Added in release 1.1.1.
