### ISSUE TITLE
Feature: Command to say URL for stats in Discord

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#11]
# Feature
The bot could have a command !stats, where it either outputs predefined message containing link to the uploaded stats. This message could be set in the config file, so you can customize it to include server/channel info and the URL for the stats.

e.g:
Ikoutone#1233: !stats
stats-bot#1324: The stats for X can be found at https://url-for-stats.com

**Comment by MJHeijster** [comment]
Added in v1.1.2.
