### ISSUE TITLE
Feature: Auto-reconnect

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#12]
# Feature

Last night I noticed that my bot had disconnected from the discord network/server. Didn't save the message it gave me, but it had disconnected by itself (not sure why, could just be a network outage on my server)

Would be good if it could automatically re-connect to the server and keep trying if it can't connect on the first try. (I run the bot in a Windows 2012 server on google cloud, so I'm not constantly monitoring it).

**Comment by MJHeijster** [comment]
Hmm that's odd, I do have a feature implemented that it should reconnect automatically. I personally monitor it with Pushover. I'll try to think of cases where it wouldn't reconnect or on ways to improve the logging.

**Comment by ikoutone** [comment]
Ah. Hopefully it was just a random edge-case that doesn't happen often. I just created a pushover account for myself. Do I just need to put the pushover user key to settings and it's good to go?

**Comment by MJHeijster** [comment]
Ah great, you might get spammed by that a lot (experience from my home server). The library I use (discord.NET) has an auto-reconnect feature that will be built into the next release, hope that fixes it in a proper way.

**Comment by MJHeijster** [comment]
It disconnected for me about 15 hours ago and I'm not sure why it didn't reconnect.. Will have to look into it further.

**Comment by MJHeijster** [comment]
It's been happening a lot on my end that the bot can't recover. I'll look further into it...

**Comment by ikoutone** [comment]
Thank you. I got a few disconnects where the bot couldn't reconnect myself as well.

**Comment by MJHeijster** [comment]
Oh boy, this has been open for a long time. It's been stable for quite a while now and I've upgraded the bot since. I do recommend using Pushover in the bot and to use the NotificationDelay so you don't get a notification when it reconnects within a specific amount of time.
