### ISSUE TITLE
[Bug]: LoggingFileName single doesn't work

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#39]
### Description

I have set loggingfilename to single, but conversation from each channel is saved in different files. 

 "Application": {
    // 	Valid options: 
    //  channelid
    //  channelname
    //  single
    "LoggingFileName": "single",
    "NotificationDelay": 30000,
    "PushOver": {

Example of what I'm getting, server.log file is from my old 1.1.2 or something version I had previously running and have manually edited so the timestamp doesn't mean anything:
![image](https://user-images.githubusercontent.com/6661689/169388375-e997d88a-757d-4d79-84bd-958269c0bd3e.png)

### Version

1.3.1

**Comment by MJHeijster** [comment]
Oof, sorry about that! I will have to look into that, I'll probably have time on Saturday for that.

**Comment by MJHeijster** [comment]
Fixed in release [V1.4.1](https://github.com/MJHeijster/StatBot/releases/tag/v1.4.1). Let me know if it's working now and if you have issues.

**Comment by ikoutone** [comment]
V1.4.1 fixed this. Conversation is saved in server.log file.
