### ISSUE TITLE
Nicknames with spaces not recognised in parser

### ISSUE THREAD

**Issue by ikoutone** [MJHeijster/StatBot#9]
# Bug

## Expected behavior
Recognise nicknames with a space

## Actual behavior
Parser doesn't recognise the nickname with a space in it.

## Steps to reproduce
- Step 1: Have user with a space in their name
- Step 2: Try to analyze log in mircstats
- Step 3: Parser doesn't recognise nick

## Logs
LINES THAT WEREN'T RECOGNIZED BY PARSER                   **
**                               Total count: 6                               **
**                                                                            **
********************************************************************************

<The Corf#6661> message

# Feature
Perhaps make the nicknames recognised by the parser by removing the space or replacing it with underscore?

**Comment by MJHeijster** [comment]
Hmm thought I already worked on this since I know about this issue. Since I can't really do anything about mircstats, I'll just replace the space with an underscore. I think I'll have the time for that this weekend.

**Comment by MJHeijster** [comment]
Added in release 1.1.1.
